### ISSUE TITLE
does this work?

### ISSUE THREAD

**Issue by luke-titley** [t-mw/force-graph-rs#3]
Hey, I spotted this on crates.io.
Does this code work ? I had a quick go at using it and can't get it to work...

**Comment by t-mw** [comment]
Hi, I've improved the documentation and added an example with the 0.3.0 release. Let me know if that helps.

**Comment by luke-titley** [comment]
Ah thanks. I dug in to why it wasn't working for me. Its the breadth first traversals in update. I can't just throw a load of nodes at it and let it position them, the first node is important. The traversal early outs and nothing is processed.

I opted to write my own in the end which is working out quite well in the end. Thank you for this update though.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by t-mw** [comment]
Ah I see, I've replaced the breadth first traversal in 0.3.2, but glad your solution is working.
